# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT AmazingQuotes.wsgi

beta_settings:
    cloud_sql_instances: amazingquotes-215218:us-central1:amazingquotesdbase

runtime_config:
  python_version: 3
# [END runtime]
